package com.cisco.iask.entity;

import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Field;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.Index;
import org.mongodb.morphia.annotations.Indexes;

/**
 * Created by sarthiya on 21/04/16.
 */

@Entity("users")
@Indexes(
	    @Index(value = "name", fields = @Field("name"))
	)
public class User {

    /**
     * Entity's unique identifier.
     */
    @Id
    private ObjectId _id;
    private String name;
    private String password;
    private String firstname;
    private String lastname;
    private String email;
    /**
     * A no-argument constructor.
     */
    public User() {
    }
    /**
     * A constructor to create employees. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public User(String firstName, String lastName, 
    	String username, String password, String e_mail
                ) {
        this.firstname = firstName;
        this.lastname = lastName;
    	this.name = username;
        this.email = e_mail;
        this.password = password;
    }
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

}
